### ISSUE TITLE
ImportError: No module named lldb

### ISSUE THREAD

**Issue by goodcyg** [everettjf/zlldb#1]
(lldb) zblock 0x102790080
error: 'zblock' is not a valid command.
然后在控制台执行main.py
Traceback (most recent call last):
  File "/../zlldb/main.py", line 3, in <module>
    import lldb 
ImportError: No module named lldb
需要到导入lldb.py?我电脑上没有找到？

**Comment by everettjf** [comment]
需要在xcode调试器下

________________________________

**Comment by goodcyg** [comment]
如何调试能写详细点吗？

**Comment by everettjf** [comment]
看下这篇文章 https://cloud.tencent.com/developer/article/1192487

**Comment by goodcyg** [comment]
好吧，。。。。。
